---
name: "CI"

on:
  push:
    branches: main
  pull_request: {}

jobs:
  linkchecker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: Link Checker
        uses: lycheeverse/lychee-action@f613c4a64e50d792e0b31ec34bbcbba12263c6a6 # v2.3.0
        with:
          # Providing default parameters plus an exclude for Google Meet which produces a network error when checked
          args: --verbose --no-progress './**/*.md' './**/*.html' --exclude https://meet.google.com
          fail: true
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

  jsonschema:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: Setup Go
        uses: actions/setup-go@0aaccfd150d50ccaeb58ebd88d36e91967a5f35b # v5.4.0
        with:
          go-version: 'stable'
      - name: Check Schema
        env:
          GOPATH: /home/runner/work/go
        run: make test
